[package]
name = "vm_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9"
volatile = "0.2"
lazy_static = { version = "1", features = ["spin_no_std"] }
spin = "0.10.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
